-- MySQL Script generated by MySQL Workbench
-- Sat Mar  6 11:16:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema topten
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `topten` ;

-- -----------------------------------------------------
-- Schema topten
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `topten` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `topten` ;

-- -----------------------------------------------------
-- Table `Members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Members` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Members` (
  `recID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TopTenLists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TopTenLists` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TopTenLists` (
  `recID` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(256) NOT NULL,
  `item1` VARCHAR(45) NOT NULL,
  `item2` VARCHAR(45) NOT NULL,
  `item3` VARCHAR(45) NOT NULL,
  `item4` VARCHAR(45) NOT NULL,
  `item5` VARCHAR(45) NOT NULL,
  `item6` VARCHAR(45) NOT NULL,
  `item7` VARCHAR(45) NOT NULL,
  `item8` VARCHAR(45) NOT NULL,
  `item9` VARCHAR(45) NOT NULL,
  `item10` VARCHAR(45) NOT NULL,
  `isPublished` VARCHAR(8) NOT NULL,
  `ownerID` INT NULL DEFAULT NULL,
  `numViews` INT NULL DEFAULT NULL,
  `numLikes` INT NULL DEFAULT NULL,
  PRIMARY KEY (`recID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
